// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb2VygiZ0O1a-E3niuoFBw17_cns3dANI',
    appId: '1:230472895213:web:b41b8d828aa4152192dae4',
    messagingSenderId: '230472895213',
    projectId: 'controlgastos-96763',
    authDomain: 'controlgastos-96763.firebaseapp.com',
    databaseURL: 'https://controlgastos-96763-default-rtdb.firebaseio.com',
    storageBucket: 'controlgastos-96763.appspot.com',
    measurementId: 'G-VV1Y4VD5NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNbtnfcEsCJCX4-onwaeZYNQ6lR2VePZU',
    appId: '1:230472895213:android:df3483fe3b6a723092dae4',
    messagingSenderId: '230472895213',
    projectId: 'controlgastos-96763',
    databaseURL: 'https://controlgastos-96763-default-rtdb.firebaseio.com',
    storageBucket: 'controlgastos-96763.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE6FdOeso4KXLC7LbrSm8xnvgVZ8Vbd9k',
    appId: '1:230472895213:ios:208f3b2ce87d4e8392dae4',
    messagingSenderId: '230472895213',
    projectId: 'controlgastos-96763',
    databaseURL: 'https://controlgastos-96763-default-rtdb.firebaseio.com',
    storageBucket: 'controlgastos-96763.appspot.com',
    iosBundleId: 'com.example.controlGastos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE6FdOeso4KXLC7LbrSm8xnvgVZ8Vbd9k',
    appId: '1:230472895213:ios:f65b291f128b6d9192dae4',
    messagingSenderId: '230472895213',
    projectId: 'controlgastos-96763',
    databaseURL: 'https://controlgastos-96763-default-rtdb.firebaseio.com',
    storageBucket: 'controlgastos-96763.appspot.com',
    iosBundleId: 'com.example.controlGastos.RunnerTests',
  );
}
