// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8QQ2q41KWouQewCApohZmhWWXHboSxAA',
    appId: '1:683396525388:web:c253f2d05f28bff52473e9',
    messagingSenderId: '683396525388',
    projectId: 'controlgastos-64bb9',
    authDomain: 'controlgastos-64bb9.firebaseapp.com',
    storageBucket: 'controlgastos-64bb9.appspot.com',
    measurementId: 'G-PHSGV00NKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKlnmr1i5xQ7y0W3oLcVc4wwuBjTV_wEg',
    appId: '1:683396525388:android:59869a08743268b72473e9',
    messagingSenderId: '683396525388',
    projectId: 'controlgastos-64bb9',
    storageBucket: 'controlgastos-64bb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQNYYiizKxO_2HpC_JQLzZ_rCX9jLeCpw',
    appId: '1:683396525388:ios:4cabaa16e3885a2c2473e9',
    messagingSenderId: '683396525388',
    projectId: 'controlgastos-64bb9',
    storageBucket: 'controlgastos-64bb9.appspot.com',
    iosBundleId: 'com.example.controlGastos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQNYYiizKxO_2HpC_JQLzZ_rCX9jLeCpw',
    appId: '1:683396525388:ios:885b121346bf51c92473e9',
    messagingSenderId: '683396525388',
    projectId: 'controlgastos-64bb9',
    storageBucket: 'controlgastos-64bb9.appspot.com',
    iosBundleId: 'com.example.controlGastos.RunnerTests',
  );
}
